In [1]:
import pandas as pd

In [2]:
dummy_nodes = pd.read_csv('hiv_raw_data/envProdsUpdated.txt', header = None)
dummy_nodes.head()

             0
0    CGT_HUMAN
1   ACHA_HUMAN
2   ACHB_HUMAN
3  A1AG1_HUMAN
4  A1AG2_HUMAN

In [3]:
human_nodes = dummy_nodes[0].str.split('_', expand=True)
len(human_nodes)

462

In [4]:
human_nodes = human_nodes[human_nodes[1]=='HUMAN']
len(human_nodes)

461

In [6]:
human_nodes['uniprot_kb_protein'] = human_nodes[0] + "_" + human_nodes[1]
human_nodes

         0      1 uniprot_kb_protein
0      CGT  HUMAN          CGT_HUMAN
1     ACHA  HUMAN         ACHA_HUMAN
2     ACHB  HUMAN         ACHB_HUMAN
3    A1AG1  HUMAN        A1AG1_HUMAN
4    A1AG2  HUMAN        A1AG2_HUMAN
..     ...    ...                ...
457  K2013  HUMAN        K2013_HUMAN
458  HACD3  HUMAN        HACD3_HUMAN
459  VTI1A  HUMAN        VTI1A_HUMAN
460   VAPA  HUMAN         VAPA_HUMAN
461  VDAC3  HUMAN        VDAC3_HUMAN

[461 rows x 3 columns]

In [9]:
human_nodes.to_csv("hiv_processed_data/human_dummy_proteins_uniprotkb.txt", index=False,columns=['uniprot_kb_protein'], header=False)

In [14]:
human_nodes_ac = pd.read_csv("hiv_processed_data/idmapping_dummy_nodes_11_04_2024.tsv", sep='\t')
human_nodes_ac

,From,Entry,Entry Name,Protein names,Gene Names
0,CGT_HUMAN,Q16880,CGT_HUMAN,2-hydroxyacylsphingosine 1-beta-galactosyltran...,UGT8 CGT UGT4
1,ACHA_HUMAN,P02708,ACHA_HUMAN,Acetylcholine receptor subunit alpha,CHRNA1 ACHRA CHNRA
2,ACHB_HUMAN,P11230,ACHB_HUMAN,Acetylcholine receptor subunit beta,CHRNB1 ACHRB CHRNB
3,A1AG1_HUMAN,P02763,A1AG1_HUMAN,Alpha-1-acid glycoprotein 1 (AGP 1) (Orosomuco...,ORM1 AGP1
4,A1AG2_HUMAN,P19652,A1AG2_HUMAN,Alpha-1-acid glycoprotein 2 (AGP 2) (Orosomuco...,ORM2 AGP2
...,...,...,...,...,...
448,K2013_HUMAN,Q8IYS2,K2013_HUMAN,Uncharacterized protein KIAA2013,KIAA2013
449,HACD3_HUMAN,Q9P035,HACD3_HUMAN,Very-long-chain (3R)-3-hydroxyacyl-CoA dehydra...,HACD3 BIND1 PTPLAD1
450,VTI1A_HUMAN,Q96AJ9,VTI1A_HUMAN,Vesicle transport through interaction with t-S...,VTI1A
451,VAPA_HUMAN,Q9P0L0,VAPA_HUMAN,Vesicle-associated membrane protein-associated...,VAPA VAP33
452,VDAC3_HUMAN,Q9Y277,VDAC3_HUMAN,Voltage-dependent anion-selective channel prot...,VDAC3

In [16]:
human_nodes_ac.to_csv("hiv_processed_data/human_dummy_nodes_uniprotAC.txt", index=False,columns=['Entry'], header=False)